version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: ascii-art
    ports:
      - "8001:8001"
    environment:
      - NAME=World
    volumes:
      - .:/app

